### ISSUE TITLE
建議伺服器增加AI 機器人系統 使最低人數維持在10~20左右

### ISSUE THREAD

**Issue by Ryder747** [paul0665/mc-goodtime#2]
建議伺服器增加AI 機器人系統 使最低人數維持在10~20左右 感觀才會比較好 (好像很多大服都會用機器人驟人數) 新玩家才不會來了馬上退服

**Comment by paul0665** [comment]
伺服器不會為了版面上的人數去做這種近似詐欺的事，現在伺服器主要問題還是設備不足導致的Lag。即使做了新玩家依然會因延遲而離開，並沒有根本上解決問題。
